---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "proxy-nginx-service"
  namespace: "default"
  labels:
    app: "proxy-nginx"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "proxy-nginx"
  type: "LoadBalancer"
  loadBalancerIP: ""

